### ISSUE TITLE
Curl isn't part of the dependencies

### ISSUE THREAD

**Issue by wilzbach** [dlang-snaps/dmd.snap#24]
From the forums: https://forum.dlang.org/post/hymrnqudfttoshuvjjxx@forum.dlang.org

**Comment by ghost** [comment]
Fixed by https://github.com/dlang-snaps/dub.snap/commit/40edef5aece8b830c79ae4528aa621b67723990c

**Comment by WebDrake** [comment]
.... and it's not about the dmd snap, but the dub snap ;-)
